### ISSUE TITLE
BreadcrumbBuilder service is not public

### ISSUE THREAD

**Issue by Jupi007** [slope-it/breadcrumb-bundle#10]
I need to add this config to `service.yaml` when I want to use it:

```yaml
SlopeIt\BreadcrumbBundle\Service\BreadcrumbBuilder:
        alias: slope_it.breadcrumb.builder
        public: true
```
